alphagov/pay-product-page

source/index.html.erb

“Components > Pay” becomes “Components > GOV.UK Pay” (requested by @roryjhs)

[PP-1562] In breadcrumbs, change “Pay” to “GOV.UK Pay”

---

README.md
bin/github-release
github-release.sh
lib/common.sh
lib/dispatch.sh
lib/github-release/cli.sh
lib/github-release/github-release.sh
lib/logging.sh

The command line script `github-release` allows you to easily build an artifact containing the generated static site and publish it on GitHub in a format that makes it suitable for use as a Node.js dependency.
Using the GitHub API, the script creates a new release from `master` with an associated tag. On your local machine, it then builds a static version of the site (using `middleman`) from your working copy, adds a `package.json` file (which makes it a Node.js module) inside the resulting `build` directory, `tar`s and `gzip`s the `build` directory, then attaches the gzipped tarball as a binary to the release in GitHub, where it appears alongside the source code downloads on the releases page. This artifact is available over HTTPS and can be used as a dependency in a Node.js project.

PP-1562 github-release script to create releases and publish on GitHub

---

source/support.html.erb

- Used `heading-medium` markup instead of `heading-2` for headings.
- Fixed typo

PP-1751 Fixed a typo and used correct markup for headings

---

source/index.html.erb

Changes:
“Central government organisations currently using GOV.UK Pay are:”
… to:
“GOV.UK Pay is working with:”

PP-2000 Update copy in ‘Who’s using GOV.UK Pay’ section

---

source/getstarted.html.erb

Update text in step 2 of getting started page to include register new account link.

PP-2368 Add register new account link to Getting Started page 

---

source/features.html.erb

* “America Express” → “American Express” (add “n” to “America”)
* “Union Pay” → “UnionPay” (remove space between “Union” and “Pay”)

Product page features page: correct some card brand names

---

source/getstarted.html.erb

Get started breadcrumb was "Get Started"
We don't use title case for things, we use sentence case.

Should be sentence case not title case

---

source/layouts/layout.erb
source/support.html.erb

Fixes a broken link (goes nowhere) on the main body of the support page to access the GOV.UK PAY service status, and also updates the footer link to go to the new statuspage.io link

PP-3119 Fixed status link on main body, and updated footer link with new statuspage.io url

---

source/cookies.html.erb

All GaaP services have been asked to update their cookies pages to link to a more modern Cookies page

BAU - better cookies info page

---

source/roadmap.html.erb

> Use ‘to’ instead of a dash or slash in date ranges. ‘To’ is quicker to read than a dash, and it’s easier for screen readers.
– https://www.gov.uk/guidance/content-design/writing-for-gov-uk#date-ranges

Use ‘to’ not hyphens for date ranges

---

source/index.html.erb

final sentence altered to make it clear that GOV.UK Pay is open to local govt, NHS and other public sector orgs

Update product page so it's less specific to central govt

---

source/getstarted.html.erb

now just says government organisations

Remove reference to "central government" on get started page

---

source/index.html.erb

While the town is called Statford-upon-Avon, the district (and the district council) is named Stratford-on-Avon

Change “Stratford-upon-Avon” to “Stratford-on-Avon” in alt text

---

source/roadmap.html.erb

IN - refund email, since we should just do it 
OUT - explicit reference to having a centrally procured card provider, until that's agreed with GBS

update roadmap for q2 2018

---

source/support.html.erb

Starter for ten, per discussion with @katiebates and @alexbishop1 about numerous support tickets received from members of the public.

Add line to support section to indicate what GOV.UK Pay support is for

---

source/cookies.html.erb
source/features.html.erb
source/getstarted.html.erb
source/payment-links.html.erb
source/privacy.html.erb
source/roadmap.html.erb
source/support.html.erb

Each page title defintion included the suffix “ - GOV.UK Pay” (e.g. “Features — GOV.UK”) but the main layout template already added this, resulting in displayed page titles like “Features - GOV.UK Pay - GOV.UK Pay”.
This change removes “ - GOV.UK Pay” from each page title definition so that the displayed titles end up like “Features - GOV.UK Pay”. The main index page remains unchaged as “GOV.UK Pay”.

Remove duplicate “ - GOV.UK Pay” from page titles

---

source/layouts/layout.erb

so that if the page opens on mobile - the navigation is
read out by screen readers, then navigation.js kicks in
and toggles the menu toggle and changes aria-hidden to true.

BAU - aria hidden boolean should be set by JS

---

source/blue-badge-scheme.html.erb

- increase awareness of using payment links if payment isn't taken upfront 
- changes "The Blue Badge service has been designed to be as self-serve as possible." to  "GOV.UK Pay is designed to be as self-serve as possible."

tiny tweaks to blue badge page

---

source/roadmap.html.erb

includes some updates to what we've done this quarter and a new section for next quarter.
- i've deleted july-september 2018 as the information is broadly available on our features page and is in the tech docs, and keeping it there risks pushing the relevant info too far down the page.
- have veered towards an optimistic list for next quarter as more likely to get feedback on features, and retrospectively deleting things we haven't done doesn't seem to have been a problem so far.

v2 update roadmap for Q4

---

source/index.html.erb

The Service Toolkit<sup>1</sup> used to categorise Government as a Platform Programme<sup>2</sup> things under ‘Components’ so the breadcrumb reflected this.
This commit also fixes the anchor link, which has also changed<sup>3</sup> to the new terminology.
1. https://www.gov.uk/service-toolkit
2. Rest in peace
3. https://www.w3.org/Provider/Style/URI

Change breadcrumb to reflect new Service Toolkit nomenclature

---

source/blue-badge-scheme.html.erb
source/cookies.html.erb
source/direct-debit.html.erb
source/features.html.erb
source/getstarted.html.erb
source/pay-product-page/stylesheets/modules/_breadcrumbs.scss
source/payment-links.html.erb
source/payment-service-provider.html.erb
source/privacy.html.erb
source/roadmap.html.erb
source/security.html.erb
source/support.html.erb

In the breadcrumbs on the subpages, replace “Components” linking to https://www.gov.uk/service-toolkit with “GOV.UK services” linking to https://www.gov.uk/service-toolkit#gov-uk-services

Breadcrumbs: replace “Components” with “GOV.UK services”

---

source/layouts/layout.erb

Move script to bottom so that DOM exists when it executes

PP-4658 - cookie banner wasnt showing because the script loaded too soon

---

Gemfile
Gemfile.lock

Middleman has updated to sassc but sprockets hasnt, so need to include
sass gem manually in the meantime
see this thread - https://github.com/middleman/middleman-sprockets/issues/132

Manually include sass gem in Gemfile

---

.github/workflows/release.yml
lib/github-release/github-release.sh

This should automatically generate a Github release whenever code gets
merged to master. The release name is based on the SHA of the commit.

Add Github action for generating release

---

.github/workflows/release.yml

The release action needs to trigger an action in pay-frontend. The only
way to do this at the moment is via repository dispatch events.

Send a repository dispatch event to pay-frontend

---

.github/workflows/release.yml

To send a dispatch event we need to use credentials that have access to
the destination repo, so I've added the CI github token as a secret to
the repo.

Use CI token for repository dispatch

---

.github/workflows/release.yml

NPM requires that all packages follow semantic versioning conventions.
Since we want to use the commit SHA as our "version", we can append this
to an actual version. See https://stackoverflow.com/questions/46967493/npm-init-and-using-non-semver-standards

Append SHA to semantic version

---

source/accessibility-statement.html.erb

We can't link to them without a payment token so it 404s which is messy
so for now removing the link as there seems to be a requirement that we
have to include the link.

PP-5653 - Remove payment service links

---

lib/github-release/github-release.sh

The script should always `cd build` before packaging.

REP-295: Fix github release script

---

README.md

We now use GitHub Actions to update the pay-product-page package in
pay-frontend, so I'm adding a description of this to the README.

REP-295: Update README with info about GH Actions

---

source/index.html.erb
source/pay-product-page/stylesheets/modules/_sub-navigation.scss

These got inadvertedly changed when migrating to GOV.UK Frontend

BAU design fixes

---

README.md

We can no longer use GitHub Actions to release the product page, so restore the old instructions for releasing a static version of the site.

PP-5950 Revert instructions for releasing static copy of site

---

source/cookies.html.erb
source/layouts/layout.erb

Description:
- Because of ICO compliance we can't store non-essential cookies so we have disabled Google Analytics as a temporary measure.
- When opt-in is enabled then we can renable Google Analytics
- Layout page has been updated to remove the 'Universal Analytics' section

PP-5977 Remove Google Analytics Pay Product

---

source/layouts/layout.erb
source/privacy.html.erb

Description:
- Because we have removed Google Analytics we have to update the information on our product pages to reflect this. Our content writer provided the needed modifications which have been updated

PP-5977 Update product pages cookie information

---

Gemfile
Gemfile.lock

There's a known issue with rack-lint which causes build failures.

BAU revert rack

---

source/govuk-payment-pages.html.erb
source/payment-service-provider.html.erb
source/support.html.erb

- Update guidance text to explain that Personally Identifiable Information should not be used in the Payment Reference or friendly web address.
- Update text in the 'Receiving your money from Stripe' section
- Update text in the 'Support' section

PP-6191 Improve Copy

---

source/pay-product-page/stylesheets/modules/_cookie-banner.scss

Was caused by the width attribute on the banner, remove this and it doesn't cause the horizontal scroll to appear.

PP-6115 Remove horizontal scroll when cookie banner displayed

---

lib/github-release/github-release.sh

Authentication using "access_token" query parameter is deprecated, so
update script to use Authorization HTTP header instead.

BAU Use Authorization header for github release

---

config.rb
source/layouts/layout.erb

Add a `new_cookie_banner` config, currently set to false. This can be set to
true manually for local development. When all the stories relating to the new
cookie banner are done - i.e. PP-6274, PP-6271 and PP-6278 -
`new_cookie_banner` can be deleted altogether.

PP-6274: feature flag for new cookie banner

---

source/api-integration.html.erb
source/apple-pay-and-google-pay.html.erb
source/direct-debit.html.erb
source/govuk-payment-pages.html.erb
source/payment-service-provider.html.erb
source/roadmap.html.erb
source/security.html.erb
source/take-payments-by-phone-or-post.html.erb
source/using-govuk-pay.html.erb

- use new content
- make subheadings medium size to be consistent with other pages
- rename page to "Security and compliance" in sidebar

PP-6246 Update security page content

---

.prettierrc
.vscode/launch.json
config.rb
package-lock.json
package.json
source/layouts/layout.erb
source/partials/_cookie-banner.erb
source/pay-product-page/javascripts/analytics/analytics.js
source/pay-product-page/javascripts/analytics/analytics.test.js
source/pay-product-page/javascripts/analytics/init.js
source/pay-product-page/javascripts/analytics/init.test.js
source/pay-product-page/javascripts/application.js
source/pay-product-page/javascripts/cookie-banner/cookie-banner.js
source/pay-product-page/javascripts/cookie-banner/cookie-banner.test.js
source/pay-product-page/javascripts/cookie-banner/test-banner-template.js
source/pay-product-page/javascripts/helpers/cookie/cookie-functions.js
source/pay-product-page/javascripts/helpers/cookie/cookie-functions.test.js
source/pay-product-page/stylesheets/modules/_cookie-banner.scss

- Add a `new_cookie_banner` config, currently set to false. This can be set to
true manually for local development. When all the stories relating to the new
cookie banner are done - i.e. PP-6274, PP-6271 and PP-6278 -
`new_cookie_banner` can be deleted altogether.
- Add new Cookie Banner JS
- Add new Analytics files
- Add Unit Test
- Add Cookie Helper Functions

PP-6274: New cookie banner

---

source/pay-product-page/javascripts/cookie-banner/cookie-banner.js
source/pay-product-page/javascripts/cookie-banner/cookie-banner.test.js

- Load analytics on page load if user has accepted cookie consent. Doesn't load analytics if cookies were rejected

PP-6278 Analytics on page load

---

config.rb
source/pay-product-page/javascripts/cookie-banner/cookie-banner.js
source/pay-product-page/stylesheets/modules/_hero-button.scss
source/pay-product-page/stylesheets/modules/_hero.scss

- Reverts 64f80b66164ec1c883c8a1472a65fb1491dd58a8 as it broken cookie banner
- Change ES6 style invocation to event handler functions
- Ignore tests from middlemand build
with @sfount, @sandorarpa, @iqbalgds

PP-6271 Fix cookie banner event handlers

---

source/layouts/layout.erb

Remove `#main` id from the href for the top banner navigation links when we are already on the page as it points to a non-existent element.
Remove redundant About link. 'About' doesn't indicate that it goes back to the landing page. To get to the landing page, it is possible to click on the logo.

PP-7089 Fix product page navigation banner links

---

source/accessibility-statement.html.erb
source/index.html.erb

This PR reflects the current status of accessibility on GOV.UK Pay.
The page has been linted and the HTML is valid, but I've not been able to do a visual check as I can't `bundle` on my work machine.

Update accessibility statement

---

source/accessibility-statement.html.erb

We intend to make GOV.UK Pay compliant with the WCAG 2.1 AA standard as soon as possible and have been working on accessibility issues for the last few weeks. This PR removes the failures we've fixed since the statement was published on 22 September.
I also removed a duplicate paragraph.

Remove the accessibility failures we've fixed

---

source/roadmap.html.erb

There's a few changes in this PR.
Instead of referencing which quarter we're in, I've put 'Things we're working on'. I've also added a 'Things we're exploring' section to differentiate that work from feature work. I've also added an 'Up next' section, to show what we're likely to work on after meeting our main objectives.
I've made these changes because I'm hoping we can update this more regularly. A roadmap is a living document.

Update roadmap with Q3 objectives

---

LICENCE
README.md

Following the [GDS Way guidelines for Licence files](https://gds-way.cloudapps.digital/manuals/licensing.html#licensing).

PP-7250 add Licence file

---

source/layouts/layout.erb

Bugs me that when we share URLs on Twitter the path gets cut off, so have added OpenGraph tags to show summary cards. Also means people don't have to decipher the URL when it's shared on Slack, they can read the OpenGraph summary card to understand what the page is about.
Just finished packing up the flat and had to wait around for someone, this seemed like a good way to pass the time.

Add OpenGraph meta tags to show cards when sharing URLs

---

source/3d-secure-2.html.erb

- We know when 3DS1 is likely to be phased out
- We now support Worldpay's Exemption Engine
- Services are strongly encouraged to enable 3DS Flex (to get 3DS2 support) as soon as possible
- Most banks ask paying users to verify themselves with a code sent by SMS

Update 3D Secure page with latest developments

---

source/cookies.html.erb

- Add text to explain the new 'govuk_pay_notifications' for  showing
the `notification banner` on the `My Services` page.

PP-7701 - Update Cookies page -  update to describe the new 'govuk_pay_notifications' cookie

---

source/payment-service-provider.html.erb

- Added 'Setting up a Stripe test account' section to GOV.UK Pay’s Payment Service Provider page

PP-7766 Add 'Setting up Stripe test account' content

---

Gemfile.lock
source/layouts/layout.erb

We're a live service now
Also rollback ffi to version 12.2.2 as there are issues building the site locally on later versions.

PP-7844 Remove beta banner

---

source/partials/_cookie-banner.erb

- This will make it easier for screen readers to navigate through the cookie banner.

PP-8015 Cookie banner - replace "aria-describedby" with "aria-label=cookie banner"

---

source/roadmap.html.erb

Have added an extra heading level to this version of the roadmap, meaning that some of the classes for headings have changed, e.g. govuk-heading-l has gone up to govuk-heading-xl, govuk-heading-m has gone up to govuk-heading-l, etc. This is so that we could introduce govuk-heading-s for h4s.

Update roadmap for April to July 2021

---

README.md

Update the instructions for releasing the product page to say that one has to run `npm install` inside frontend after updating the product page dependency.

PP-8091 Release instructions should say to npm install frontend

---

source/pay-product-page/javascripts/analytics/init.js
source/pay-product-page/javascripts/analytics/init.test.js

- Fix issue with domain for Google Analytics cookie.
- Set the domain when running the command `ga('create'...)`

PP-8519 Google Analytics - Set domain on Google Analytics cookie

---

lib/github-release/github-release.sh

For some reasons, sometimes when I do a release, the script the creates a tarball not of the `build` directory but of the directory above, which at that point does not seem to contain a `build` directory. It then merrily uploads this to GitHub. This is kind of dangerous, so check we’re actually in the `build` directory before creating the tarball.

BAU — Check in build directory when building release tarball

---

source/security.html.erb

- these documents are confidential and should be only available to authenticated users.

BAU remove hyperlinks to confidential docs

---

source/layouts/layout.erb

- The privacy notice hosted on `pay-product-page` was updated to be specific for paying users only
- The payment pages will continue to link to this privacy notice.
- A new privacy notice was added to `self service` specifically for public sector users.
- Therefore, the `footer` privacy notice link is updated to  link to the `self service > privacy notice`

PP-10242 Footer - link to the Self service privacy notice

---

source/privacy.html.erb

This matches the capitalisation in Worldpay’s privacy policy.

BAU — Change ‘WorldPay’ to ‘Worldpay’ in privacy policy

---

config.rb

Following on from the good work done in
https://github.com/alphagov/pay-product-page/pull/665
Address the build issues, keep the rule that should work with the static GitHub Pages deployment.
Specifying `.txt.html` instructs the static file generated to use the appropriate `Content-Type` for the snipper 
of HTML that is generated to appropriately redirect the user accessing this path.
This removes the other instructions as they collide with the existing `/security` page (otherwise defined in this repo) and cause the build to fail.
Note the `page` config seems to only instruct the `middleman serve` process, not the static files generated -- this isn't validated but the behaviour suggests it.
Supersedes https://github.com/alphagov/pay-product-page/pull/668

PP-11087 Fix redirecting security text to cabinet office

---

.github/workflows/run-tests.yml
.github/workflows/static.yml

For a recent story, building the website failed but the PR was only blocked when the the post-merge build and release Github action workflow was run.
We should add a GitHub actions check to PR builds to ensure the products pages can be built using bundle exec middleman build. It would also be useful to run with the --verbose flag, otherwise the cause of a failure might not be shown.
- add build static website to PR test

PP-11338 add build static website to PR

---

source/apple-pay-and-google-pay.html.erb

Removed outdated references and tidied up text for style

PP-11756 Update page as digital wallets are now live

---

source/recurring-payments.html.erb

Current wording might imply it is only available to services in the beta status, ie not fully live yet. This edit aims to make it clearer that that's not true

Remove potential ambiguity about who can sign up

---

source/roadmap.html.erb

Updated the Roadmap page, with new information for 2023/24

pp-11615 Update Roadmap Page

---

source/cookies.html.erb

Remove the gateway_account cookie from the [cookies](https://www.payments.service.gov.uk/cookies/) page because we stopped using this cookie a year ago (PP-10413).
Also change ‘Javascript’ to ‘JavaScript’ per https://www.gov.uk/guidance/style-guide/technical-content-a-to-z, which says: “Capital J, capital S.”

BAU — Remove gateway_account cookie

---

.github/workflows/static.yml
.github/workflows/visual-regression.yml
README.md

Long overdue renaming of the default branch, to avoid outdated language and be consistent with our other repositories. 
~I'll rename the branch in the settings shortly after creating this PR.~ The branch has now been renamed to `main`.
This PR changes the post-deploy and visual regression workflows to trigger on merges to the main branch.

PP-12761: Rename default branch

---

source/accessibility-statement.html.erb

Change the last updated date of the accessibility statement to 28 October 2024 since that’s the date the revised version actually went live.

PP-12053 Change accessibility statement updated date to 28 October

---

.github/workflows/run-tests.yml
.github/workflows/static.yml
.github/workflows/visual-regression.yml

Updates the following actions:
- `actions/checkout`
- `actions/setup-node`
- `ruby/setup-ruby` (3rd party safelist has been updated in the settings)
- `actions/configure-pages`
- `actions/github-script`
- `actions/upload-artifact` and `actions/deploy-pages` (need to be upgraded together for compatibility)
The post-merge workflow action upgrades worked OK for the team manual (see https://github.com/alphagov/pay-team-manual/pull/2203), so I'm reasonably confident they won't break the deployment here either.

PP-12244: Resolve GitHub Actions deprecation warnings

---

.github/workflows/_run-tests.yml
.github/workflows/pr.yml
.github/workflows/static.yml

We want to run the [shared `dependency-review` action workflow](https://github.com/alphagov/pay-ci/pull/1329) on pull requests in this repository, to replace the existing Snyk checks.
The main app repositories have a dedicated `pr.yml` workflow file, with a shared `_run-tests.yml` workflow called pre- and post-merge. 
In an attempt to get the repository workflows in a consistent state, I've:
- added a new `pr.yml` workflow
- renamed the `run-tests` job to `tests`
- added a call to the `detect-secrets` workflow as it was missing from this repo
Finally, I've included the `dependency-review` action in the `pr.yml` workflow.
I've kept `visual-regression.yml` as a separate workflow file as it is only triggered on certain PRs.
**Note**: Moving the tests workflow also means adjusting the …

PP-12687: Add dependency review checks

---

source/privacy.html.erb

In our privacy policy, update the link to Worldpay’s privacy policy from the current URL (which no longer exists) to the new [Worldpay Privacy Center](https://privacy.worldpay.com/policies/en).

PP-13688 Fix Worldpay privacy policy link

---

.percy.json
.secrets.baseline
config.rb
package-lock.json
package.json
source/javascripts/analytics/analytics.js
source/javascripts/analytics/init.js
source/javascripts/analytics/init.test.js
source/javascripts/application.js
source/javascripts/cookie-banner/cookie-banner.js
source/javascripts/cookie-settings/cookie-settings.js
source/javascripts/cookies.js
source/layouts/layout.html.erb
source/required-responsible-person-and-director-information.html.erb

Co-authored by: @marcotranchino
Make changes as per the V5 release notes: https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0
Included doing the following:
- Update JS to work with ES6 format used by V5

PP-12322 - Upgrade to govuk-frontend V5

---

source/index.html.erb

With this change, we are updating the copy for our home page for three sections.
---

PP-13870 Update 3 grid rows on product-page

---

source/index.html.erb

Update the description metadata for the main page at https://www.payments.service.gov.uk/ to be:
> GOV.UK Pay is for central government, local authorities, police and the NHS. It lets them take payments quickly, easily and securely.
This is used in two `meta` elements as the value of the `content` attribute:
- The `meta` element with a `name` attribute of `description` as specified at https://html.spec.whatwg.org/#meta-description
- The `meta` element with a `property` attribute of `og:description` — that is, the Open Graph `og:description` tag specified at https://developers.facebook.com/docs/sharing/webmasters/#basic

PP-13953 Update description metadata for main page

---

source/index.html.erb
source/stylesheets/modules/_hero.scss

- Change heading from “Take online payments from your users” to “The best way to take payments for public services”.
- Change text from “If you work in the public sector, use GOV.UK Pay to take payments” to “GOV.UK Pay has contracts with payment providers so you can take payments quickly and easily. It’s used across central and local government, police and the NHS.”
- Change button text from “Create a test account” to “Find out if you can use GOV.UK Pay”.
- Remove “or find out what GOV.UK Pay offers” alternative action.
- Deviate from the [product-page-example](https://github.com/alphagov/product-page-example/) by making it so that the inline image (shown on narrow screens like mobile phones) appears under the text and above the button rather than under the heading and above the text. Add …

PP-13869 Update main page masthead

---

source/index.html.erb
source/stylesheets/modules/_hero.scss

We think the breakage we saw was caching related and only temporary and we’re willing to live with it.
Reverts alphagov/pay-product-page#826

Revert "Revert "PP-13869 Update main page masthead""

---

source/index.html.erb

Remove the alt text "A helpful inline error message responds to user input"

PP-14039Ccorrect typo  in alt text on homepage

---

source/index.html.erb

With this change, we are updating the What’s new section on the home page in order to make it more purposeful.
In particular we are mentioning that we are planning to start using Pay By Bank to make payments faster and cheaper.
We are continuing to link to our roadmap.

PP-14025 Update What’s new section on Home page

---

.secrets.baseline
source/layouts/layout.html.erb

Updating the metatags in the layout so that it pulls in the correct assets. See below (specifically the favicon) for changes before (main branch):
And after (`rebrand_june_2025` branch):

PP-14184 update metatags and favicon

---

source/layouts/layout.html.erb

- The links to the cookies and accessibility page are using relative links - which can produce the wrong link depending on where you are navigating from.
- Adding a `/` so they are starting from the root.

PP-14278 - Fix footer links

---

source/stylesheets/modules/_sub-navigation.scss

- No longer shows an underline if you hover over a focused link in the sub navigation.
Adds an extra underline when you hover over a focused link in the sub navigation:
No underline is added when you hover over the focused link.
The underline now looks thinner.

PP-14263 Fix sub nav links underline bug

---

Gemfile.lock

Dependabot opened a couple of PRs, one with high and another with low security alert.
Github says that the files are out-of-date with base branch. However, dependabot is not reacting to rebase commands.

BAU update Gemlock for security alerts
