source/index.html.erb, source/layouts/layout.erb, source/pay-product-page/stylesheets/modules/_hero-button.scss, source/support.html.erb
Added a call to action on the product page and a support page that this call to action links to.
This support page sits within the product page domain and has information about how to get
in touch with Pay. The support link in the header also goes to this page.
=> PP-1751 Added a call to action on the product page and a support page that this call to action links to

config.rb, source/index.html.erb, source/layouts/layout.erb, source/pay-product-page/stylesheets/modules/_govuk-logo.scss, source/pay-product-page/stylesheets/modules/_header.scss, source/pay-product-page/stylesheets/modules/_masthead.scss
Little fixes we spotted after going live 🙄
=> PP-2247 product page 2.0 post launch fixes 

source/layouts/layout.erb, source/pay-product-page/javascripts/application.js, source/pay-product-page/javascripts/cookies.js, source/pay-product-page/stylesheets/_core.scss, source/pay-product-page/stylesheets/modules/_cookie-banner.scss
=> PP-2434 - adding cookie banner to product page as we are storing GA cookie

source/layouts/layout.erb
Details here — https://docs.google.com/document/d/1vc8SFsQ9k059YLv0XLG1uas03G2AYkWh3HhyCUlTJyE/edit
=> Update tracking to Gaap standard

source/index.html.erb
So that "Pay" doesn't wrap on to next line on it's own.
=> Update every instance of GOV.UK Pay to non-breaking space

config.rb
in case a 3rd party is linking to /contact I've set up a redirect
=> PP-3057 - contact => support redirect 

source/getstarted.html.erb
Old ticket raised by Tim based on a regular query that comes into DeskPro, this makes it clearer
=> PP-2651 - adding guidance on how long an integration takes

source/roadmap.html.erb
Added all the remaining quarters for this year
=> Updated roadmap for 2018

source/getstarted.html.erb, source/index.html.erb, source/layouts/layout.erb
Updated documentation url to new service url
solo @belindac
=> PP-3379 Change documentation link in header and footer

source/self-service-payments.html.erb
@soniaturcotte wrote better ones with me
=> PP-3554 - update alt texts

source/features.html.erb
Added a paragraph to show the new feature and link to feature page
=> Add Self Service payments to feature page

source/roadmap.html.erb
=> Adjusted the roadmap to reflect priorities for next mission

source/index.html.erb
Users will see responsive payment pages
Designed to meet user needs, the payment pages give helpful inline error messages and work great on mobile.
Designed to meet user needs
The payment pages give helpful inline error messages and are responsive across devices
=> PP-3687 - copy update

source/layouts/layout.erb, source/pay-product-page/stylesheets/_core.scss, source/pay-product-page/stylesheets/modules/_sticky.scss, source/privacy-notice.html.erb
Adding a page for the privacy notice and adding to the footer.
Also used position: sticky for the sidebar as the page is long and will
make it easy to navigate, there is pretty good browser support for it
these days and in the spririt of progressive enhancement I think it’s ok
if some users wont get it.
=> PP-3769 - Introduce privacy notice

source/pay-product-page/stylesheets/modules/_sticky.scss, source/privacy.html.erb
Updating words to match this doc
https://docs.google.com/document/d/1rfmf8Piy9kj8mxI8OnLzyqLPvxA12FBu9zqmKDIKA7A/edit?ts=5b02a63c#
Also sticky nav on mobile made it overlay on the content
=> BAU - tweaks to the privacy notice content

source/privacy.html.erb
Removing until content team decide what link to replace it with
=> BAU - remove dead link

source/index.html.erb, source/pay-product-page/stylesheets/_core.scss, source/pay-product-page/stylesheets/modules/_case-study.scss, source/pay-product-page/stylesheets/modules/_content-section.scss
Also a little copy update for PP-4085
=> PP-4089 - add case study to homepage

source/self-service-payments.html.erb
Adding video to payments link page as responsive embed
=> PP-4171 - adding video to payment links page

source/roadmap.html.erb
still needs a proper content review, but describes what we've been doing and will be doing better
=> updating the roadmap to describe q2 and q3 better

source/features.html.erb
copy of this https://github.com/alphagov/pay-product-page/pull/73
=> BAU - Adding @kaitiebates updated feature page

source/payment-links.html.erb
Changes a few instances per title of this PR.
Note: there are still some images which refer to "self service".
=> 'Self service' -> 'Payment links'

source/features.html.erb, source/index.html.erb
Mark spoke to Katie about some copy tweaks just adding them now
=> BAU - Copy updates

source/blue-badge-scheme.html.erb
=> Change “EPDQ” to “ePDQ” on Blue Badge page

source/index.html.erb, source/layouts/layout.erb
- Pages should have the html lang set
- Pages should have a meta description
=> BAU - improvement to page meta

source/features.html.erb
removing DD reference from main body as some people think we offer it when we don't 
creating new features section which asks for beta partners for DD
=> New features section on Features page

source/blue-badge-scheme.html.erb
please check hyperlinks closely, thanks!
=> Updates to BB page

source/roadmap.html.erb
deletes last quarter
adds next quarter 
extends later to 2019-20
@tillwirth to confirm
=> Q4 2018-9 updates to roadmap

source/features.html.erb
changes only to the "Choose your Payment Service Provider" section
based on Tracy's content here: https://docs.google.com/document/d/1omaLv_DQBNsC95pRLSYJCmR8OHNgcvRVqEVmyBVHQAk/edit?usp=sharing
=> amends to features page to update with Stripe contract

source/features.html.erb, source/roadmap.html.erb, source/security.html.erb
Last section contains placeholder content, just waiting on Mark
=> Adding new security page

source/getstarted.html.erb
Preview — https://build-d23yqetoh.now.sh/getstarted/
=> PP-4918 - update copy with new go live steps

source/features.html.erb, source/payment-service-provider.html.erb, source/roadmap.html.erb, source/security.html.erb
=> BAU - add page about our PSP (Stripe)

source/direct-debit.html.erb, source/features.html.erb, source/payment-links.html.erb, source/payment-service-provider.html.erb, source/roadmap.html.erb, source/security.html.erb
This is temporary fix until we do a better overall nav
=> BAU - add payments links to sidebar nav

source/direct-debit.html.erb
clarifies success rate for DDs and changes pilot to test
=> clarifications

source/roadmap.html.erb
https://docs.google.com/document/d/1Cu4JKIjgxXHpBJjoBVbv0M9Wx2zCWaSx2BrEFrOPBMA/edit?ts=5cb06d5e# - content 
would be good to check headers since i've used two H2 headers in succession - is there an H3 that could be used instead for "In progress" and "Coming next"?
Thanks!
=> Updates roadmap content and contact details etc

source/features.html.erb
- adds payment links in welsh 
- clarifies what you have to do with test/ live account
=> additions to features page

source/index.html.erb
... good luck!!! GOV.UK Pay is in good hands.
=> Katie's the boss now!!

source/support.html.erb
.... good luck! Pay is in good hands!
=> Katie's the boss now

source/features.html.erb
This PR updates the features sub-section of the Pay product page with direct debit with some modifications to 'Manage Payment and Reports.'
=> BAU updates features page to include direct debit

source/layouts/layout.erb
Thanks @yahoopete for spotting this!
=> BAU - Slack changed the link

source/direct-debit.html.erb
=> makes it clear DD is ready to use

source/payment-service-provider.html.erb
Seems odd that we mention Worldpay and Barclaycard, but not Stripe
=> makes it clear that we use Stripe

source/roadmap.html.erb
maybe this should also include updating to v3 of DS to meet accessibility regs...
=> updating roadmap for q2 2019-20

source/accessibility-statement.html.erb, source/layouts/layout.erb
You can see a preview of how it looks here https://pay-product-page-test.cloudapps.digital/accessibility-statement/
=> PP-5653 add accessibility statement

source/pay-product-page/stylesheets/modules/_hero.scss
=> BAU - add govuk-frontend accessible focus state

source/direct-debit.html.erb, source/getstarted.html.erb, source/roadmap.html.erb
Updating copy to match this doc https://docs.google.com/document/d/1xOCN3_HrqiafbdAV1I_2JNWRl1icqBOm7xHcWK8Zph4/edit?ts=5dc16a52&pli=1
=> Update a bunch of pages

source/layouts/layout.erb
Description:
- Added ERB tags on single line rather than multiline
=> BAU-Fix-banner

source/govuk-payment-pages.html.erb
- Fixed copy, removed extra word
=> PP-6191 Fix copy for Payment Links

source/payment-service-provider.html.erb
- Add missing line for Stripe copy: If you want to change this description, just contact the GOV.UK Pay team.
=> PP-6191 Update copy for Stripe > Receving Payouts

source/api-integration.html.erb, source/apple-pay-and-google-pay.html.erb, source/direct-debit.html.erb, source/govuk-payment-pages.html.erb, source/payment-service-provider.html.erb, source/security.html.erb, source/take-payments-by-phone-or-post.html.erb, source/using-govuk-pay.html.erb
Content from https://docs.google.com/document/d/1-CfAQ9pUKfMOKAZWUayhBYyq84Gxwkmv32sQfGqxjtM/edit
=> PP-6181 Add MOTO product page

source/pay-product-page/javascripts/analytics/analytics.js, source/pay-product-page/javascripts/analytics/analytics.test.js, source/pay-product-page/javascripts/analytics/init.js, source/pay-product-page/javascripts/analytics/init.test.js, source/pay-product-page/javascripts/application.js, source/pay-product-page/javascripts/cookie-banner/cookie-banner.js, source/pay-product-page/javascripts/cookie-banner/cookie-banner.test.js, source/pay-product-page/javascripts/helpers/cookie/cookie-functions.js, source/pay-product-page/javascripts/helpers/cookie/cookie-functions.test.js
- Changed JS namespace name from 'window.GovPay' to 'window.GovUkPay'
=> PP-6274 Cookie Banner - renamed JS namespace

config.rb, source/pay-product-page/javascripts/cookie-banner/cookie-banner.js
- Update Config.rb
- Remove invalid JS in cookie-banner.js
=> PP-6271 Update files to get Build working

jest.config.js, source/pay-product-page/javascripts/cookie-banner/cookie-banner.test.js, source/pay-product-page/javascripts/cookie-settings/cookie-settings.test.js, source/pay-product-page/javascripts/helpers/cookie/cookie-functions.js, source/pay-product-page/javascripts/helpers/cookie/cookie-functions.test.js
- Set cookie domain on analytics so the cookie can be shared with other apps
All tests passes
=> PP-6443 Fix cookie domain

source/cookies.html.erb
=> PP-6443 Cookie Page - fix typo

source/pay-product-page/javascripts/cookie-settings/cookie-settings.js, source/pay-product-page/javascripts/cookie-settings/cookie-settings.test.js
- Use full referrer rather then just pathname
=> PP-6443 Fix referrer link

source/direct-debit.html.erb
- Update text on direct debit page
=> PP-6243 Update Direct Debit page

README.md
Add clear steps and remove superfluous information.
=> BAU Improve release instructions

source/govuk-payment-pages.html.erb, source/payment-service-provider.html.erb
Update govuk-payment-pages and payment-service-provider pages.
=> PP-6678 update settlement reporting and reporting columns

source/roadmap.html.erb
We've updated the roadmap for Q2 2020-21, featuring everything that we're working on now and later, plus everything we've recently released.
=> Update the roadmap for Q2 2020-21

source/api-integration.html.erb, source/apple-pay-and-google-pay.html.erb, source/roadmap.html.erb, source/take-payments-by-phone-or-post.html.erb
Fix broken links to tech docs to reflect new tech docs navigation
=> Fix broken links to tech docs

source/3d-secure-2.html.erb
Add a new page detailing 3D Secure 2
=> PP-6805 add page for 3ds 2

source/3d-secure-2.html.erb
- correct the link to the moto payments documentation
=> PP-6805 correct moto payments url

.gitignore, source/api-integration.html.erb, source/blue-badge-scheme.html.erb, source/getstarted.html.erb, source/govuk-payment-pages.html.erb, source/payment-service-provider.html.erb, source/police.html.erb, source/take-payments-by-phone-or-post.html.erb, source/using-govuk-pay.html.erb
- update pages' content according to this document: https://docs.google.com/document/d/14A4fDRALCq0tbMZMvZCZ7jztxchG8K-5FTkbB9OICAw
=> PP-6821 update the product pages to stop Bring Your Own Contract

source/getstarted.html.erb, source/using-govuk-pay.html.erb
- some context/styling was missed in the first round. Correct these according to the document:
https://docs.google.com/document/d/14A4fDRALCq0tbMZMvZCZ7jztxchG8K-5FTkbB9OICAw
=> PP-6821 correct text according to the document

source/layouts/layout.erb
In order to gain access to Search Console, we need to update the Google site verification code.
=> Update Google site verification

source/accessibility-statement.html.erb, source/index.html.erb
from https://github.com/alphagov/pay-product-page/pull/274
=> Accessibility statement - Address review comments

source/direct-debit.html.erb
=> Update the Direct Debit page

source/3d-secure-2.html.erb
=> Remove details from 3D Secure 2 page

source/accessibility-statement.html.erb
We've taken in the latest changes thanks to the PaaS team and updated Statuspage's CSS. I've also reviewed any outstanding points against JIRA tickets and we've completed some failures. Have also updated all required dates in the statement.
=> Update accessibility statement

source/accessibility-statement.html.erb
Two silly errors that wouldn't have happened if my job title was 'Developer' instead of 'Product manager'. Sorry!
=> Removed bullet point, closed list tag

source/roadmap.html.erb
- Added a 'What we're learned through research' section
- Updated what we're working on and what we've released
- Shuffled things around in the 'Up next' and 'Later' sections
Some discrete items from the roadmap from last quarter have been absorbed into the discoveries.
=> Update roadmap for January to March 2021

source/layouts/layout.erb
- add a new navigation link, called Features to the top nav bar
=> PP-7725 add Features navigation link

source/index.html.erb, source/layouts/layout.erb
Performance platform has been retired so remove this link.
=> PP-7923 Remove link to performance platform

source/privacy.html.erb
This is collected as part of Strong Customer Authentication and anti-fraud measures.
=> Add IP address to privacy policy

source/privacy.html.erb
- Related to privacy policy updated for collecting user IP address https://github.com/alphagov/pay-product-page/pull/312
=> PP-8008 Update privacy policy 'last updated date'

bin/github-release, lib/build.sh
- Added build step so latest copy of the site is built before uploading to Github
=> BAU - build static html before release

source/getstarted.html.erb
Description:
- Content change - see corresponding JIRA ticket
=> PP-8010 - Update content for demo session

source/getstarted.html.erb
use a registration link rather than public link
=> PP-8691 update zoom link

data/performance.json
- BAU update performance stats 04/10/21
=> BAU update performance stats 04/10/21

source/cookies.html.erb, source/recaptcha-notice.html.erb
- Add reCAPTHA notice page
- Add section to cookiet page for reCAPTCHA cookie
=> PP-8684 Add reCAPTCHA notice

data/performance.json
- BAU update performance stats 15/11/21
=> BAU update performance stats 15/11/21

data/performance.json
- BAU update performance stats 30/11/21
=> BAU update performance stats 30/11/21

data/performance.json
- BAU update performance stats 13/12/21
=> BAU update performance stats 13/12/21

data/performance.json
- BAU update performance stats 20/12/21
=> BAU update performance stats 20/12/21

data/performance.json
- BAU update performance stats 10/01/22
=> BAU update performance stats 10/01/22

.secrets.baseline, source/layouts/layout.erb
- Update the Google Verification code.
- Remove the old & unused Google analytics code from the layout.erb
=> PP-9909 Update Google Verification code & remove old Google Analytics.

data/performance.json
- BAU update performance stats 17/01/22
=> BAU update performance stats 17/01/22

source/accessibility-statement.html.erb
- Remove the text about the error for Paying users as this has been fixed.
- Update the review date for the Status Page accessibility improvements.
- Update the review date.
=> ZD-482302 Review and update the Accessiblity Page

data/performance.json
- BAU update performance stats 25/01/22
=> BAU update performance stats 25/01/22

data/performance.json
- BAU update performance stats 25/04/22
=> BAU update performance stats 25/04/22

data/performance.json
- BAU update performance stats 09/05/22
=> BAU update performance stats 09/05/22

data/performance.json
- BAU update performance stats 16/05/22
=> BAU update performance stats 16/05/22

data/performance.json
- BAU update performance stats 30/05/22
=> BAU update performance stats 30/05/22

data/performance.json
- BAU update performance stats 20/06/22
=> BAU update performance stats 20/06/22

source/security.html.erb
- Re-added the updated links to the security page.
=> PP-9744 fix security page links

data/performance.json
- BAU update performance stats 05/09/22
=> BAU update performance stats 05/09/22

data/performance.json
- BAU update performance stats 12/09/22
=> BAU update performance stats 12/09/22

source/required-responsible-person-and-director-information.html.erb
Home address is a required field.
=> PP-10183 Add missing information

data/performance.json
- BAU update performance stats 17/10/22
=> BAU update performance stats 17/10/22

source/api-integration.html.erb, source/blue-badge-scheme.html.erb, source/cost-benefits-of-pay.html.erb, source/getstarted.html.erb, source/govuk-payment-pages.html.erb, source/police.html.erb, source/using-govuk-pay.html.erb
Update the create account links to link to the new start page for the registration journey - /register/email-address.
=> PP-10061 Update create account links

data/performance.json
- BAU update performance stats 19/12/22
=> BAU update performance stats 19/12/22

data/performance.json
- BAU update performance stats 09/01/23
=> BAU update performance stats 09/01/23

data/performance.json
- BAU update performance stats 16/01/23
=> BAU update performance stats 16/01/23

source/privacy.html.erb
- Move the `know your rights` section so that it is after `Childrens proctection policy`.
- Add the `know your rights` section to the sub navigation.
=> PP-10242 Privacy page - move `know your rights` section

data/performance.json
- BAU update performance stats 06/02/23
=> BAU update performance stats 05/02/23

.github/workflows/run-tests.yml, .github/workflows/static.yml, .github/workflows/visual-regression.yml, .percy.json, package-lock.json, package.json, source/partials/_features-sub-nav.html.erb
- GHA to trigger visual regression testing if the source directory has been modified
- this workflow is configured to only run when the source directory has been modified. Otherwise, we're generating snapshots for content identical to the base build
- percy configuration 
- exclusions are in place for pages we strictly redirect from
=> PP 10667 GHP preview production pipeline

.github/workflows/visual-regression.yml
When the main branch is updated we need to refresh Percy's known gold standard
=> PP-10667 update main branch percy build on merge

data/performance.json
- BAU update performance stats 17/04/23
=> BAU update performance stats 17/04/23

source/humans.txt.erb
=> PP-10698 add humans.txt

data/performance.json
- BAU update performance stats 15/05/23
=> BAU update performance stats 15/05/23

data/performance.json
- BAU update performance stats 05/06/23
=> BAU update performance stats 05/06/23

data/performance.json
- BAU update performance stats 13/06/23
=> BAU update performance stats 13/06/23

.github/dependabot.yml
See RFC: https://github.com/alphagov/pay-architecture/discussions/97
=> PP-11138: Set Dependabot to create security updates only

data/performance.json
- BAU update performance stats 24/07/23
=> BAU update performance stats 24/07/23

data/performance.json
- BAU update performance stats 20/11/23
=> BAU update performance stats 20/11/23

data/performance.json
- BAU update performance stats 18/12/23
=> BAU update performance stats 18/12/23

package-lock.json, package.json
- This means the app will use the new crown assets.
=> PP-12187 Update govuk-frontend to 3.15

source/security.html.erb
There are some errors on our security and compliance page.
- fix content
=> PP-12482 Content changes to security and compliance page

data/performance.json
- update performance stats 08/07/24
=> BAU update performance stats 01/08/24

data/performance.json
- update performance stats 29/07/24
=> BAU update performance stats 29/08/24

data/performance.json
- update performance stats 19/08/24
=> BAU update performance stats 19/08/24

source/accessibility-statement.html.erb
@alanmaddrell  did a pretty substantial rewrite https://payments-platform.atlassian.net/browse/PP-12053
Had some issues with the original PR:
- Created with Github UI tool which has caused issues before.
- Some prettier linting issues.
- Bug with an apostrophe.
Issuse are fixed and had to create a new PR
=> PP-12053 - Update accessibility-statement.html.erb

data/performance.json
- update performance stats 23/12/24
=> BAU update performance stats 23/12/24

data/performance.json
- update performance stats 06/01/25
=> BAU update performance stats 06/01/25

source/using-govuk-pay.html.erb
https://payments-platform.atlassian.net/browse/PP-13426 add more info about reporting
=> Add more info about reporting

data/performance.json
- corrected service name - update performance stats 10/02/25
=> BAU update performance stats 10/02/25 - corrected

data/performance.json
Update stats to show 100 million payments
=> BAU update performance stats 100M payments

data/performance.json
- update performance stats 07/04/25
=> BAU update performance stats 07/04/25

source/index.html.erb
=> PP-13868 Update copy with correct curly apostrophe

source/index.html.erb
=> PP-13993 remove extra space

source/index.html.erb
- Update hidden text in the `Who's using GOV.UK Pay ` section.
=> PP-13867 Update hidden accessibility text

source/layouts/layout.html.erb
Updating footer by adding raw html from https://govuk-frontend-review.herokuapp.com/components/header . See difference before and after screen shots below:
**Before:**
**After:**
=> PP-13940 update footer

data/performance.json
- update performance stats 16/06/25
=> BAU update performance stats 16/06/25
